language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - CI_VERSION=3.0.0

# install this project on top of it
install:
  composer install

# run multiple test commands
script:
  - phpunit                  #default test command
  - phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test
