language: php
php:
	- 5.1
	- 5.2
	- 5.3
	- 5.4
	- 5.5
	- 5.6
	- hhvm

matrix:
	allow_failures:
		- php: 5.1
		- php: 5.2
		- php: 5.3
		- php: hhvm
	fast_finish: true

env:
	- CI_VERSION=3.0.0

# install this project on top of it
install:
	composer install

# run multiple test commands
script:
	- phpunit                  #default test command
	- phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test