language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

#Just check HTML validation for now

install:
 - "pip install html5validator"
script: "html5validator"
