language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: 5.3
        - php: hhvm
        - php: nightly
    fast_finish: true

env:
    - CI_VERSION=3.0.0

# update build enviroment
before_install:
    php /home/travis/.phpenv/versions/5.5/bin/composer self-update

# install this project on top of it
install:
    composer install

# run multiple test commands
script:
    - phpunit                  #default test command
    - phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test